config/routes.rb
Rails.application.routes.draw do
  
  get 'admin' => 'admin#index'
  get 'home' => 'home#show'
  get 'opportunities' => 'opportunities#all'
  #get 'opportunities/:id' => 'opportunities#show', as: 'opportunity'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  root 'home#index', as: 'home_index'
  resources :accounts do
    resources :opportunities
  end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_secure_password
  after_destroy :ensure_an_admin_remains
  has_many :accounts
  enum role: {
    "Admin" => 1,
    "User" => 2
  }
  validates :role, inclusion: roles.keys
  class Error < StandardError
  end
  private
    def ensure_an_admin_remains
      if User.count.zero?
        raise Error.new "Can't delete last user"
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :only_admin, only: %i[ new index create edit update destroy]
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :get_accounts, only: %i[ show ]
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    if @user.role == "Admin" || @user.id == session[:user_id]
      redirect_to users_url, notice: "Can't delete user"
    else
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_path, notice: "User was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end
  rescue_from 'User::Error' do |exception|
    redirect_to users_url, notice: exception.message
  end
    

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    def get_accounts
      @accounts = Account.where(user_id: params[:id])
    end 
    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :role)
    end
end

app/helpers/users_helper.rb
module UsersHelper
 
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <%= form.text_field :role, value: "User", hidden: true %>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control" %>
  </div>

   <div class="actions mt-3">
      <div class="row">
        <div class="col">
          <%= link_to 'Cancel', :back, class: "btn btn-primary form-control btn-block" %> 
        </div>
        <div class="col">
          <%= submit_tag "Submit", class: "btn btn-primary form-control btn-block" %>
        </div>
        <% if user.id? %>
        <div class="col">
          <%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-primary form-control btn-block" %> 
        </div>
        <% end %>
      </div>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New User', new_user_path, class: "btn btn-primary" %>

<h1 class="text-center m-2">Users</h1>

<div class="row">
  <% @users.each do |user| %>
    <div class="col-md-4 col-sm-12 mb-4">
      <%= link_to user, class: "text-decoration-none", style: "color: black;" do %>
        <div class="card">
          <div class="card-header">
            <%= user.name %>
          </div>
          <div class="card-body">
             <strong> Role: </strong> <%= user.role %><br>
              <strong> User Accounts: </strong><%= user.accounts.count %>
          </div>
          <div class="card-footer p-2">
            <div class="row">
              <div class="col">
                <%= link_to 'Edit', edit_user_path(user), class: "btn btn-sm btn-primary form-control btn-block" %> 
              </div>
              <div class="col">
                <%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-primary form-control btn-block" %> 
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h4 class="text-center">
  <strong>Name:</strong>
  <%= @user.name %><br>
  <strong>Role:</strong>
  <%= @user.role %>
</h4>
<h1>Accounts</h1>
<div>
  <div class="row">
    <% @accounts.each do |account| %>
      <div class="col-lg-4 col-sm-12">
        <%= link_to account, class: "text-decoration-none", style: "color: black;" do %>
          <div class="card linkable mt-3">
            <div class="card-header">
              <%= account.name %>
            </div>
              <div class="card-body">
                  <h5 class="card-title">Address: <%= account.address %></h5>
                  <p class="card-text">Available Opportunities: <%= account.opportunities.count %> </p>
              </div>
               <% if session[:user_id] && account.user_id == session[:user_id] || admin? %>
                <div class="card-footer p-2">
                  <div class="row">
                    <div class="col">
                      <%= link_to 'Edit', edit_account_path(account), class: "btn btn-sm btn-primary form-control btn-block" %>
                    </div>
                    <div class="col">
                      <%= link_to 'Delete', account, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-primary form-control btn-block"%>
                    </div>
                  </div>
                </div>
              <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>