config/routes.rb
Rails.application.routes.draw do
  
  get 'admin' => 'admin#index'
  get 'home' => 'home#show'
  get 'opportunities' => 'opportunities#all'
  #get 'opportunities/:id' => 'opportunities#show', as: 'opportunity'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  root 'home#index', as: 'home_index'
  resources :accounts do
    resources :opportunities
  end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authorize
  ACCOUNTS_SIZE = 4
  OPPS_SIZE = 10
  def index
    @users = User.where(role: "Admin")
  end
  def show
    @page = (params[:page] || 0).to_i
    @sage = (params[:sage] || 0).to_i
    @accounts = Account.offset(ACCOUNTS_SIZE * @page).limit(ACCOUNTS_SIZE)
    @opportunities = Opportunity.offset(OPPS_SIZE * @sage).limit(OPPS_SIZE)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="text-center">
  <h1>Welcome to Opportunity Management System</h1>
  <%= link_to 'Get Started', home_url, :class => "btn start btn-lg btn-outline-primary m-3"  %>
  <div class="card m-5">
    <h4 class="mt-3">Demo Account</h4>
    <% if !@users.empty? %>
      <% @users.each do |user| %>
      <p><strong>Admin</strong></p>
      <p>username: <%= user.name %></p>
      <p>password: 12345678 </p>
      <% end %>
    <% end %>
    <p class="text-danger">Note: only Admin can create user accounts</p>
  </div>
  <div>
  
  </div>
</div>

app/views/home/show.html.erb
<p id="notice"><%= notice %></p>

 <div class="row">
   <div class="col-lg-4">
     <div class="container card">
      <% if session[:user_id] %>
        <%= link_to 'Create Account', new_account_path, class: "btn btn-primary mt-2" %>
      <% end %><br>
      <h3>Company Accounts</h3>
      <div>
        <div class="row margin-twenty5-zero margin-b-zero pagination-row">
          <% @accounts.each do |account| %>
            <div class="col-12">
              <%= link_to account, class: "text-decoration-none", style: "color: black;" do %>
                <div class="card linkable mt-3 pagination">
                  <div class="card-header">
                    <%= account.name %>
                  </div>
                    <div class="card-body">
                        <h5 class="card-title">Address: <%= account.address %></h5>
                        <p class="card-text">Available Opportunities: <%= account.opportunities.count %> </p>
                    </div>
                  <% if session[:user_id] && admin? %>
                    <div class="card-footer p-2">
                      <div class="row">
                        <div class="col">
                          <%= link_to 'Edit', edit_account_path(account), class: "btn btn-sm btn-primary form-control btn-block" %> 
                        </div>
                        <div class="col">
                          <%= link_to 'Delete', account, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-primary form-control btn-block" %> 
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>
              <% end %>
            </div>
          <% end %>
          <div class="pager table pt-4">
            <ul id="horizontal-list">
                <li class="previous <%= @page == 0 ? 'disabled' : '' %> btn btn-outline-primary float-left">
                    <%= link_to_if @page > 0, "Previous", home_path(page: @page - 1) %>
                </li>

                <li class="next btn float-right mr-3">
                    <%= link_to "Next", home_path(page: @page + 1) %>
                </li>
            </ul>
          </div>
        </div>
      </div>
    </div>  
  </div>
  <br>
  <div class="col-lg-8 p-lg-4 pt-sm-5">
    <div class="container">
      <h1>Available Opportunities</h1>
      <div>
        <div class="row">
          <% @opportunities.each do |opportunity| %>
            <div class="col-lg-6">
               <div class="card linkable mt-3">
                    <div class="head card-header text-truncate">
                      <%= opportunity.name %> from <%= Account.find_by(id: opportunity.account_id).name %>
                    </div>
                      <div class="card-body">
                          <h5 class="card-title">Stage: <%= opportunity.stage %></h5>
                          <p class="card-text">Amount: <%= opportunity.amount %> </p>
                      </div>
                  </div> 
            </div>
          <% end %>
          <div class="pager table pt-4">
            <ul id="horizontal-list">
                <li class="previous <%= @sage == 0 ? 'disabled' : '' %> btn btn-outline-primary float-left">
                    <%= link_to_if @sage > 0, "Previous", home_path(sage: @sage - 1) %>
                </li>

                <li class="next btn float-right mr-3">
                    <%= link_to "Next", home_path(sage: @sage + 1) %>
                </li>
            </ul>
          </div>
        </div>
      </div>
    </div>  
  </div>
 </div> 