config/routes.rb
Rails.application.routes.draw do
  
  get 'admin' => 'admin#index'
  get 'home' => 'home#show'
  get 'opportunities' => 'opportunities#all'
  #get 'opportunities/:id' => 'opportunities#show', as: 'opportunity'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  root 'home#index', as: 'home_index'
  resources :accounts do
    resources :opportunities
  end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Opportunity Management System</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=0.8">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'styles' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-fixed-top navbar-dark bg-primary mb-4 pl-lg-5 pr-lg-5">
          <a class="navbar-brand" href="/">OMSystem</a>
          <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse-1"  aria-controls="navbar-collapse-1" aria-label="Toggle navigation" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse " id="navbar-collapse-1">
          <ul class="navbar-nav ml-auto mr-5-lg">
            <li class="nav-item <%= 'active' if current_controller?('home') %>"><a class="nav-link" href="/home">Home</a></li>
            <li class="nav-item <%= 'active' if current_controller?('opportunities') %>"><%= link_to 'Opportunities', opportunities_url, class: "nav-link"  %></li>
            <li class="nav-item <%= 'active' if current_controller?('accounts') %>"><%= link_to 'Accounts', accounts_path, class: "nav-link"  %></li>
              <% if session[:user_id] %>
                <% if User.find_by(id: session[:user_id]).role == "Admin" %>
                  <li class="nav-item <%= 'active' if current_controller?('users') %>"><%= link_to 'Users', users_path, class: "nav-link" %></li>
                <% end %>
                <li class="nav-item <%= 'active' if current_controller?('session') %>"><%= link_to 'Logout', logout_path, method: :delete, class: "nav-link"  %></li>
              <% else %>
                <li class="nav-item <%= 'active' if current_controller?('session') %>"><%= link_to 'Login', users_path, class: "nav-link" %></li>
              <% end %>
          </ul>
        </div>
    </nav>
    <main class='<%= controller.controller_name %>'>
      <div class="container">
        <div class="card mt-3">
          <%= link_to 'Back', :back, class: "w-25 back mr-lg-3 mt-lg-3 btn btn-primary ml-auto" %>
          <div class="card-body">
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>