config/routes.rb
Rails.application.routes.draw do
  
  get 'admin' => 'admin#index'
  get 'home' => 'home#show'
  get 'opportunities' => 'opportunities#all'
  #get 'opportunities/:id' => 'opportunities#show', as: 'opportunity'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  root 'home#index', as: 'home_index'
  resources :accounts do
    resources :opportunities
  end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/account.rb
class Account < ApplicationRecord
  validates :name, :address, presence: true
  validates :name, uniqueness: true
  has_many :opportunities, dependent: :destroy
  belongs_to :user

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  skip_before_action :authorize, only: %i[ show index ]
  before_action :set_account, only: %i[ show edit update destroy ]
  before_action :check_current_account, only: %i[ edit update destroy]
  # GET /accounts or /accounts.json
  def index
    @accounts = Account.where(user_id: session[:user_id])
    @list_accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to accounts_path, notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to accounts_path, notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_path, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end
    def check_current_account
      if session[:user_id] != @account.user_id && User.find_by(id: session[:user_id]).role != "Admin"
        redirect_to accounts_path, notice: "You are unauthorized to perform this action!"
      end
    end
    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:name, :address, :user_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <% if admin? && !current_page?(:controller => 'accounts', :action => 'new') && account.persisted?  %>
   <div class="field form-group">
      <%= form.number_field :user_id, value: account.user.id ,class: "form-control", hidden: true %>
    </div>
  <% else %>
    <div class="field">
       <%= form.number_field :user_id, value: session[:user_id] ,class: "form-control", hidden: true  %>
    </div>
  <% end%>
  <div class="field form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="actions mt-2">
    <div class="row">
      <div class="col">
        <%= link_to 'Cancel', :back, class: "btn btn-primary form-control btn-block" %> 
      </div>
      <div class="col">
        <%= submit_tag "Submit", class: "btn btn-primary form-control btn-block" %>
      </div>
      <% if @account.id? %>
      <div class="col">
         <%= link_to 'Delete', account, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-primary form-control btn-block" %>
      </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>
<%= render 'form', account: @account %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>
<% if session[:user_id] %>
  <%= link_to 'Create Account', new_account_path, class: "btn btn-primary float-right" %>
<% end %>
<% if session[:user_id] %>
<h1>Your Accounts</h1>
<div>
  <div class="row">
    <% @accounts.each do |account| %>
      <div class="col-lg-4 col-sm-12">
        <%= link_to account, class: "text-decoration-none", style: "color: black;" do %>
          <div class="card linkable mt-3">
            <div class="card-header">
              <%= account.name %>
            </div>
              <div class="card-body">
                  <h5 class="card-title">Address: <%= account.address %></h5>
                  <p class="card-text">Available Opportunities: <%= account.opportunities.count %> </p>
              </div>
            <% if (session[:user_id] && account.user_id == session[:user_id]) %>
              <div class="card-footer p-2">
                <div class="row">
                  <div class="col">
                    <%= link_to 'Edit', edit_account_path(account), class: "btn btn-sm btn-primary form-control btn-block" %> 
                  </div>
                  <div class="col">
                    <%= link_to 'Delete', account, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-primary form-control btn-block" %> 
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<% else %>
<h1>Company Accounts</h1>
<div>
  <div class="row">
    <% @list_accounts.each do |account| %>
      <div class="col-lg-4 col-sm-12">
        <%= link_to account, class: "text-decoration-none", style: "color: black;" do %>
          <div class="card linkable mt-3">
            <div class="card-header">
              <%= account.name %>
            </div>
              <div class="card-body">
                  <h5 class="card-title">Address: <%= account.address %></h5>
                  <p class="card-text">Available Opportunities: <%= account.opportunities.count %> </p>
              </div>
            <% if (session[:user_id] && account.user_id == session[:user_id]) %>
              <div class="card-footer p-2">
                <div class="row">
                  <div class="col">
                    <%= link_to 'Edit', edit_account_path(account), class: "btn btn-sm btn-primary form-control btn-block" %> 
                  </div>
                  <div class="col">
                    <%= link_to 'Delete', account, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-primary form-control btn-block" %> 
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<% end %>

app/views/accounts/new.html.erb
<h1>Create Account</h1>
<%= render 'form', account: @account %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<% if session[:user_id] && @account.user_id == session[:user_id] %>
  <%= link_to 'Edit ' + @account.name, edit_account_path(@account), class: "btn btn-primary" %> 
  <%= link_to 'Create Opportunity', new_account_opportunity_path(@account), class: "btn btn-small btn-outline-primary" %>
<% end %>
<h2 class="text-center">
  <%= @account.name %>
</h2>

<p class="text-center">
  <strong>Address:</strong>
  <%= @account.address %>
</p>
<hr>
<% if !@account.opportunities.empty? %>
<div class="header"> 
  <h2>Available Opportunities</h2>
</div>
  <div class="card-body">
    <div class="row">
      <% for opportunity in @account.opportunities %>
        <div class="col-sm-6 col-lg-4">
          <%= link_to account_opportunity_path(@account, opportunity), class: "text-decoration-none", style: "color: black;" do %>
            <div class="card linkable mt-3">
                <div class="card-header head">
                  <%= opportunity.name %>
                </div>
                
                <div class="card-body">
                  <h5 class="card-title"><%= opportunity.stage %></h5>
                  <p class="card-text">Ksh <%= opportunity.amount %></p>
                </div>
                <% if session[:user_id] && @account.user_id == session[:user_id] || admin? %>
                  <div class="card-footer p-2">
                    <div class="row">
                      <div class="col">
                        <%= link_to 'Edit', edit_account_opportunity_path(@account, opportunity), class: "btn btn-sm btn-primary form-control btn-block" %>
                      </div>
                      <div class="col">
                        <%= link_to 'Delete', [@account, opportunity], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-primary form-control btn-block"%>
                      </div>
                    </div>
                  </div>
                <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
<h4 class="m-5 text-center">No Opportunities available! <% if !session[:user_id] %>Come back later. <% end %> </h4>
<% end %>